[database]
url = "postgres://user:password@localhost/dbname"

[http]
url = "http://localhost:8080"
secure = false
secret = "-------------------------------------------------"

[smtp]
domain = "domain.com"
user = "no-reply@domain.com"
pass = "pass"

[files]
static_dir = "./static"
templates_dir = "./templates"

